// Prints SQL that gives the demo relocation the fixed sample plan (the same
// stand-in plan the tests use), so the demo can be clicked through without an
// AI key. Run: npx tsx scripts/sample-plan-sql.ts
import { mockPlan } from "../src/lib/planner/mock";
import { applyPolicy } from "../src/lib/planner/policy";
import type { PolicyConfig } from "../src/lib/planner/schema";

const ASSIGNMENT = "40000000-0000-0000-0000-000000000001";
const TENANT = "10000000-0000-0000-0000-000000000001";
const policy: PolicyConfig = {
  services: {
    immigration: { covered: true, max_cost: 150000 },
    flights: { covered: true, max_cost_per_person: 45000 },
    temporary_housing: { covered: true, max_days: 30, max_cost: 350000 },
    household_goods: { covered: true, max_cost: 400000 },
    school_search: { covered: true, max_cost: 60000 },
    settling_in: { covered: true, max_cost: 80000 },
  },
};
const request = {
  employeeName: "Eshan Employee (Demo)",
  familySize: 3,
  origin: "Bengaluru, India",
  destination: "Dubai, UAE",
  moveDate: "2026-11-15",
  budget: 1500000,
};

const q = (s: string) => `'${s.replaceAll("'", "''")}'`;
const arr = (xs: string[]) => `array[${xs.map(q).join(", ")}]::text[]`;
const plan = applyPolicy(mockPlan(request), policy, request.familySize);

const lines: string[] = [];
lines.push("-- Sample plan for the demo relocation (generated by scripts/sample-plan-sql.ts).");
lines.push("-- Only applied while the demo plan is still pending.");
lines.push("with target as (");
lines.push(`  select 1 from public.relocation_plans where assignment_id = ${q(ASSIGNMENT)} and status = 'pending'`);
lines.push("), svc as (");
lines.push("  insert into public.plan_services (assignment_id, rmc_tenant_id, service_key, category, title, description,");
lines.push("    sequence, depends_on, start_date, due_date, estimated_cost, policy_status, policy_note, approval_required, approval_reason)");
lines.push("  select v.* from target, (values");
lines.push(
  plan.services
    .map(
      (s) =>
        `    (${q(ASSIGNMENT)}::uuid, ${q(TENANT)}::uuid, ${q(s.key)}, ${q(s.category)}, ${q(s.title)}, ${q(s.description)}, ${s.sequence}, ${arr(s.depends_on)}, ${q(s.start_date)}::date, ${q(s.due_date)}::date, ${s.estimated_cost}, ${q(s.policy_status)}, ${q(s.policy_note)}, ${s.approval_required}, ${q(s.approval_reason)})`,
    )
    .join(",\n"),
);
lines.push("  ) as v");
lines.push("  returning 1");
lines.push("), ms as (");
lines.push("  insert into public.plan_milestones (assignment_id, rmc_tenant_id, title, due_date, sequence, related_service_keys)");
lines.push("  select v.* from target, (values");
lines.push(
  plan.milestones
    .map((m) => `    (${q(ASSIGNMENT)}::uuid, ${q(TENANT)}::uuid, ${q(m.title)}, ${q(m.due_date)}::date, ${m.sequence}, ${arr(m.related_service_keys)})`)
    .join(",\n"),
);
lines.push("  ) as v");
lines.push("  returning 1");
lines.push(")");
lines.push("update public.relocation_plans");
lines.push(`set status = 'ready', summary = ${q(plan.summary.replace("Six services", "Sample plan: six services"))},`);
lines.push("    model = 'sample-plan', attempts = 1, generated_at = now(), updated_at = now()");
lines.push(`where assignment_id = ${q(ASSIGNMENT)} and status = 'pending' and (select count(*) from svc) > 0 and (select count(*) from ms) > 0;`);
lines.push(`update public.assignments set status = 'planned' where id = ${q(ASSIGNMENT)} and status = 'requested';`);
console.log(lines.join("\n"));
